### ISSUE TITLE
Support 1inch Fusion

### ISSUE THREAD

**Issue by tnd3** [mraniki/dxsp#198]
@mraniki fantastic helper library in active current development unlike others!  :+1: 
Based on everything happening with CEX users do need **DEX** :shipit: 

**Please** see [1inch Fusion](https://1inch.io/fusion) + [Fusion SDK ](https://github.com/1inch/fusion-sdk) only ***18*** lines of code.

- [x] Auto Routing
- [x] Liquidity Aggregation
- [x] Zero gas fees
- [ ] Check slippage e.g < -2%
- [ ] Check price impact e.g < -1%
- [ ] Split % Order Amount into e.g 3 chunks to get best price
- [ ] Logging for BUY / SELL = % Profits (PnL) :tada:

Using Tradingview alert Webhook to DiFi bot to execute DEX trades.

**Comment by mraniki** [comment]
Yeah that is definitely the goal. thanks for the encouragement. check my dex trading tool (https://github.com/mraniki/tt). Problem with 1inch is that they are blocking now their api. so main option via uni swapv2 type router is the best approach. I'm exploring Apollox as there is forex now on their V2 but no documentation yet

**Comment by tnd3** [comment]
More encouragement for active project 🥇 

I am supporting with comments elsewhere to point people here:

:iphone: :phone:
See the [TalkyTrader ](https://talky.readthedocs.io/en/latest/)project by [@mraniki](https://github.com/mraniki) here:
https://github.com/mraniki/tt

Python DEX Token Swap Library:
https://github.com/mraniki/dxsp

**Comment by mraniki** [comment]
@tnd3 built has been done but there is an issue with 1inch api being tracked here
https://github.com/mraniki/dxsp/issues/189
Until this is resolved by 1inch we only have normal router access via uniswap lib or 0x access
